# Generated by Django 4.2.3 on 2023-07-12 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("supercats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="upload",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
    ]
